/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reverse Location */
        get: operations["reverseLocation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drillings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Drilling */
        post: operations["createDrilling"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drillings/{drilling_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Drilling */
        get: operations["getDrilling"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Coordinates */
        Coordinates: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** CountryResult */
        CountryResult: {
            /** Name */
            name: string;
            /** Iso A2 */
            iso_a2: string | null;
            /** Iso A3 */
            iso_a3: string | null;
        };
        /** DestinationResult */
        DestinationResult: {
            /**
             * Type
             * @enum {string}
             */
            type: "land" | "ocean";
            country: components["schemas"]["CountryResult"] | null;
            state: components["schemas"]["StateResult"] | null;
            nearest_place: components["schemas"]["PlaceResult"] | null;
            nearest_land: components["schemas"]["NearestLandResult"] | null;
        };
        /** DrillingAccepted */
        DrillingAccepted: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Status Url */
            status_url: string;
        };
        /** DrillingCreate */
        DrillingCreate: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Origin Label */
            origin_label?: string | null;
        };
        /** DrillingResponse */
        DrillingResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Stage */
            stage: string;
            origin: components["schemas"]["Coordinates"];
            antipode: components["schemas"]["Coordinates"] | null;
            destination: components["schemas"]["DestinationResult"] | null;
            /** Origin Label */
            origin_label: string | null;
            /** Destination Label */
            destination_label: string | null;
            /** Destination Is Land */
            destination_is_land: boolean | null;
            /** Nearest Place */
            nearest_place: string | null;
            /** Nearest Place Distance M */
            nearest_place_distance_m: number | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NearestLandResult */
        NearestLandResult: {
            coordinates: components["schemas"]["Coordinates"];
            /** Distance Km */
            distance_km: number;
            country: components["schemas"]["CountryResult"] | null;
            nearest_place: components["schemas"]["PlaceResult"] | null;
        };
        /** PlaceResult */
        PlaceResult: {
            /** Name */
            name: string;
            /** Country */
            country: string | null;
            coordinates: components["schemas"]["Coordinates"];
            /** Distance Km */
            distance_km: number;
        };
        /** ReverseGeocodingResponse */
        ReverseGeocodingResponse: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Display Name */
            display_name: string;
            /** Address */
            address: {
                [key: string]: string;
            };
            /** Cached */
            cached: boolean;
        };
        /** StateResult */
        StateResult: {
            /** Name */
            name: string;
            /** Admin */
            admin: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    reverseLocation: {
        parameters: {
            query: {
                lat: number;
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReverseGeocodingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createDrilling: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DrillingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrillingAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDrilling: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                drilling_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrillingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
